### ISSUE TITLE
Grey hulk shakes

### ISSUE THREAD

**Issue by jeanfbrito** [fernandoporazzi/then-and-now#1]
grey image shakes on fast move of the slider

**Comment by fernandoporazzi** [comment]
Hi, @jeanfbrito, unfortunately I did not get to cause the problem. I've tested in Chrome and Firefox and it seems ok. I've moved the mouse as fast as I could and it worked fine.

I don't know what to do to solve this. If you got a solution, please, send a pull request. It will be very appreciated.

**Comment by jeanfbrito** [comment]
Only happens on Chrome 43.0.2357.65 m. Firefox works fine. May be a version problem.
